image: node:latest

before_script:
- apt-get update -qy
- apt-get install -y ruby-dev
- gem install dpl

stages:
 - heroku

heroku:
 stage: heroku
 image: ruby:latest
 script:
  - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/olx-arbisoft.git
  - git push -f heroku main

 only:
 - main
