# Generated by Django 3.2.9 on 2022-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='short_description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
